### ISSUE TITLE
bug: pass wrong params

### ISSUE THREAD

**Issue by yjl9903** [hydrati/maria2#13]
https://github.com/hydrati/maria2/blob/6b0b857866c89d6f2240a8ed4a6a2932a25ad3ba/src/open.ts#L223-L233

I think we should not pass the methodName as the first args here.

<img width="787" alt="image" src="https://github.com/hydrati/maria2/assets/30072175/73879745-15bc-45d0-8661-5dd1725d1820">

**Comment by hydrati** [comment]
Thanks.
