### ISSUE TITLE
Types of Multicall are incorrect 

### ISSUE THREAD

**Issue by yjl9903** [hydrati/maria2#16]
https://github.com/yjl9903/naria2/blob/8383183d3d8ad61f43c8a966115045e020a8f88e/patches/maria2%400.3.2.patch#L25-L31

I have forgotten what is wrong here 😂, but I did some patches to make it more make sense.

**Comment by hydrati** [comment]
It seems that the response structure of multicall is wrong.
It'll be check this Sat and be fix. :) @yjl9903
